<?php

namespace AppBundle\Repository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends \Doctrine\ORM\EntityRepository
{

    public function recupClient($login, $motDePasse)
    {
        $res = $this->_em->getRepository('AppBundle:Client');

        $user = $res->findOneBy(array("login" => $login, "mdp" => $motDePasse));

        return $user;
    }

}
